function asyncGeneratorStep(y,w,I,J,F,D,A){try{var G=y[D](A),B=G.value}catch(K){I(K);return}G.done?w(B):Promise.resolve(B).then(J,F)}function _asyncToGenerator(y){return function(){var w=this,I=arguments;return new Promise(function(J,F){function D(B){asyncGeneratorStep(G,J,F,D,A,"next",B)}function A(B){asyncGeneratorStep(G,J,F,D,A,"throw",B)}var G=y.apply(w,I);D(void 0)})}}
function _typeof(y){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(w){return typeof w}:function(w){return w&&"function"===typeof Symbol&&w.constructor===Symbol&&w!==Symbol.prototype?"symbol":typeof w};return _typeof(y)}var _regenerator;
(function(){var y=function(w){function I(a,b,c,l){b=Object.create((b&&b.prototype instanceof F?b:F).prototype);l=new L(l||[]);b._invoke=K(a,c,l);return b}function J(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(l){return{type:"throw",arg:l}}}function F(){}function D(){}function A(){}function G(a){["next","throw","return"].forEach(function(b){a[b]=function(c){return this._invoke(b,c)}})}function B(a,b){function c(d,q,x,z){d=J(a[d],a,q);if("throw"===d.type)z(d.arg);else{var v=d.arg;return(d=
v.value)&&"object"===_typeof(d)&&C.call(d,"__await")?b.resolve(d.__await).then(function(H){c("next",H,x,z)},function(H){c("throw",H,x,z)}):b.resolve(d).then(function(H){v.value=H;x(v)},function(H){return c("throw",H,x,z)})}}var l;this._invoke=function(d,q){function x(){return new b(function(z,v){c(d,q,z,v)})}return l=l?l.then(x,x):x()}}function K(a,b,c){var l=m;return function(d,q){if(l===u)throw Error("Generator is already running");if(l===e){if("throw"===d)throw q;return O()}c.method=d;for(c.arg=
q;;){if(d=c.delegate)if(d=P(d,c)){if(d===k)continue;return d}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(l===m)throw l=e,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);l=u;d=J(a,b,c);if("normal"===d.type){l=c.done?e:h;if(d.arg===k)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(l=e,c.method="throw",c.arg=d.arg)}}}function P(a,b){var c=a.iterator[b.method];if(c===E){b.delegate=null;if("throw"===b.method){if(a.iterator["return"]&&
(b.method="return",b.arg=E,P(a,b),"throw"===b.method))return k;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return k}c=J(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,b.delegate=null,k;c=c.arg;if(!c)return b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,k;if(c.done)b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=E);else return c;b.delegate=null;return k}
function Q(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function M(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function L(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(Q,this);this.reset(!0)}function N(a){if(a){var b=a[n];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function d(){for(;++c<a.length;)if(C.call(a,c))return d.value=a[c],d.done=!1,d;d.value=
E;d.done=!0;return d};return b.next=b}}return{next:O}}function O(){return{value:E,done:!0}}var R=Object.prototype,C=R.hasOwnProperty,E,t="function"===typeof Symbol?Symbol:{},n=t.iterator||"@@iterator",r=t.asyncIterator||"@@asyncIterator",g=t.toStringTag||"@@toStringTag";w.wrap=I;var m="suspendedStart",h="suspendedYield",u="executing",e="completed",k={};t={};t[n]=function(){return this};var f=Object.getPrototypeOf;(f=f&&f(f(N([]))))&&f!==R&&C.call(f,n)&&(t=f);var p=A.prototype=F.prototype=Object.create(t);
D.prototype=p.constructor=A;A.constructor=D;A[g]=D.displayName="GeneratorFunction";w.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===D||"GeneratorFunction"===(a.displayName||a.name):!1};w.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,A):(a.__proto__=A,g in a||(a[g]="GeneratorFunction"));a.prototype=Object.create(p);return a};w.awrap=function(a){return{__await:a}};G(B.prototype);B.prototype[r]=function(){return this};w.AsyncIterator=B;w.async=function(a,
b,c,l,d){void 0===d&&(d=Promise);var q=new B(I(a,b,c,l),d);return w.isGeneratorFunction(b)?q:q.next().then(function(x){return x.done?x.value:q.next()})};G(p);p[g]="Generator";p[n]=function(){return this};p.toString=function(){return"[object Generator]"};w.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function d(){for(;b.length;){var q=b.pop();if(q in a)return d.value=q,d.done=!1,d}d.done=!0;return d}};w.values=N;L.prototype={constructor:L,reset:function(a){this.next=this.prev=
0;this.sent=this._sent=E;this.done=!1;this.delegate=null;this.method="next";this.arg=E;this.tryEntries.forEach(M);if(!a)for(var b in this)"t"===b.charAt(0)&&C.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=E)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(v,H){q.type="throw";q.arg=a;c.next=v;H&&(c.method="next",c.arg=E);return!!H}if(this.done)throw a;for(var c=this,l=this.tryEntries.length-1;0<=
l;--l){var d=this.tryEntries[l],q=d.completion;if("root"===d.tryLoc)return b("end");if(d.tryLoc<=this.prev){var x=C.call(d,"catchLoc"),z=C.call(d,"finallyLoc");if(x&&z){if(this.prev<d.catchLoc)return b(d.catchLoc,!0);if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else if(x){if(this.prev<d.catchLoc)return b(d.catchLoc,!0)}else if(z){if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-
1;0<=c;--c){var l=this.tryEntries[c];if(l.tryLoc<=this.prev&&C.call(l,"finallyLoc")&&this.prev<l.finallyLoc){var d=l;break}}d&&("break"===a||"continue"===a)&&d.tryLoc<=b&&b<=d.finallyLoc&&(d=null);c=d?d.completion:{};c.type=a;c.arg=b;return d?(this.method="next",this.next=d.finallyLoc,k):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===
a.type&&b&&(this.next=b);return k},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),M(c),k}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var l=a.arg;M(c)}return l}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:N(a),resultName:b,nextLoc:c};"next"===this.method&&
(this.arg=E);return k}};return w}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=y}catch(w){Function("r","_regenerator = r")(y)}})();
(function(){function y(t){var n=null;t==seraph_accel.Gen.hr.E_CONTEXT_EXPIRED?n=C("OpSrvCtxExpired","admin.Manage","seraphinite-accelerator"):seraph_accel.Gen.hr.Fail(t)&&(n=E(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),t));return n}function w(){w=_asyncToGenerator(_regenerator.mark(function r(n){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return jQuery(n).attr("disabled",!0),g.prev=1,g.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:g.next=8;break;case 6:g.prev=6,g.t0=g["catch"](1);case 8:jQuery(n).attr("disabled",!1);case 9:case "end":return g.stop()}},r,this,[[1,6]])}));return w.apply(this,arguments)}function I(){I=_asyncToGenerator(_regenerator.mark(function g(n,r){var m,h,u,e,k,f;return _regenerator.wrap(function(p){for(;;)switch(p.prev=p.next){case 0:m=jQuery(n.parentNode).closest(".blck").first();h=m.find(".seraph_accel_spinner");m.find(".content");u=
m.find('input[type="button"]:not(.cancel)');e=m.find('input[type="button"].cancel');if(!r){p.next=23;break}u.prop("disabled",!0);h.show();seraph_accel.Manager._int.notRefreshStat=!0;k=null;p.prev=10;p.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:f=p.sent;seraph_accel.Gen.hr.Fail(f)&&(k=E(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),f));p.next=20;break;case 17:p.prev=17,
p.t0=p["catch"](10),k="HTTP "+p.t0.status;case 20:return k&&(alert(k),u.prop("disabled",!1),h.hide()),delete seraph_accel.Manager._int.notRefreshStat,p.abrupt("return");case 23:return e.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,k=null,p.prev=26,p.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:f=p.sent;k=y(f);p.next=37;break;case 33:p.prev=33,p.t1=p["catch"](26),
k="HTTP "+p.t1.status,e.prop("disabled",!1);case 37:k&&alert(k),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return p.stop()}},g,this,[[10,17],[26,33]])}));return I.apply(this,arguments)}function J(t){switch(t){case 0:return C("OpDescr_Invalidate","admin.Manage","seraphinite-accelerator");case 3:return C("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return C("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return C("OpDescr_SrvDel",
"admin.Manage","seraphinite-accelerator")}return""+t}function F(){F=_asyncToGenerator(_regenerator.mark(function r(n){var g,m,h,u;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),m=g.find('input[type="button"].cancel'),m.prop("disabled",!0),h=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:u=
e.sent;h=y(u);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),h="HTTP "+e.t0.status;case 14:h&&alert(h);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return F.apply(this,arguments)}function D(){D=_asyncToGenerator(_regenerator.mark(function r(n){var g,m,h,u;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),m=g.find('input[type="button"].cancel'),m.prop("disabled",!0),h=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:u=e.sent;h=y(u);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),h="HTTP "+e.t0.status;case 14:h&&alert(h);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return D.apply(this,arguments)}function A(){A=_asyncToGenerator(_regenerator.mark(function r(n){var g,m,h,u,e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),m=g.find(".seraph_accel_spinner"),
h=g.find('input[type="button"]:not(.cancel)'),u=g.find('input[type="button"].cancel'),m.show(),h.prop("disabled",!0),u.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,e=null,f.prev=9,f.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:k=f.sent;e=y(k);f.next=19;break;case 16:f.prev=16,f.t0=f["catch"](9),e="HTTP "+f.t0.status;case 19:e&&alert(e),delete seraph_accel.Manager._int.notRefreshExtDp;
case 21:case "end":return f.stop()}},r,this,[[9,16]])}));return A.apply(this,arguments)}function G(){G=_asyncToGenerator(_regenerator.mark(function r(n){var g,m,h,u;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),m=g.find('input[type="button"].cancel'),m.prop("disabled",!0),h=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdCancel",{}),type:"POST",data:"",
cache:!1,dataType:"json"});case 7:u=e.sent;h=y(u);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),h="HTTP "+e.t0.status;case 14:h&&alert(h);case 15:case "end":return e.stop()}},r,this,[[4,11]])}));return G.apply(this,arguments)}function B(){B=_asyncToGenerator(_regenerator.mark(function m(n,r,g){var h,u,e,k,f,p,a,b,c,l,d,q,x,z;return _regenerator.wrap(function(v){for(;;)switch(v.prev=v.next){case 0:return h=jQuery(n.parentNode).closest(".blck").first(),u=h.find(".seraph_accel_spinner"),e=h.find(".descr"),
k=h.find('input[type="button"]:not(.cancel)'),f=h.find('input[type="button"].cancel'),p=h.find("#seraph_accel_views"),a=h.find("#seraph_accel_geos"),b=[],p.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(p.get()),b=seraph_accel.Ui.TokensList.GetVal(p.get())),c=[],a.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(a.get()),c=seraph_accel.Ui.TokensList.GetVal(a.get()).filter(function(H){return"_"!==H})),d=String(h.find(".type").val()),"uri"===d?l=h.find(".uri").val():0===d.indexOf("uri:")&&(l=d.substr(4),
d="uri"),l=seraph_accel.Gen.StrReplaceAll(String(l),["\r","\n","*"],["",";","{ASTRSK}"]),u.show(),e.show(),e.text(J(r)),k.prop("disabled",!0),f.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,q={cache:!1,dataType:"json"},512>l.length?q.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:d,op:r,uri:l,v:b.join(),g:c.length?c.join():void 0,_wpnonce:g}):(q.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",
{type:d,op:r,v:b.join(),g:c.length?c.join():void 0,_wpnonce:g}),q.type="POST",q.contentType="application/x-www-form-urlencoded",q.data="uri="+encodeURIComponent(l)),x=null,v.prev=23,v.next=26,jQuery.ajax(q);case 26:z=v.sent;x=y(z);v.next=33;break;case 30:v.prev=30,v.t0=v["catch"](23),x="HTTP "+v.t0.status;case 33:x&&alert(x),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return v.stop()}},m,this,[[23,30]])}));return B.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function m(n,
r,g){var h,u,e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return h=jQuery(n.parentNode).closest(".blck").first(),u=h.find('input[type="button"].cancel'),u.prop("disabled",!0),e=null,f.prev=4,f.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:r,_wpnonce:g}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:k=f.sent;e=y(k);f.next=14;break;case 11:f.prev=11,f.t0=f["catch"](4),e="HTTP "+f.t0.status;case 14:e&&
alert(e);case 15:case "end":return f.stop()}},m,this,[[4,11]])}));return K.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function m(n,r,g){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},m,this)}));return P.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function m(n,r,g){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},m,this)}));return Q.apply(this,
arguments)}function M(){M=_asyncToGenerator(_regenerator.mark(function m(n,r,g){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},m,this)}));return M.apply(this,arguments)}function L(){L=_asyncToGenerator(_regenerator.mark(function g(n,r){return _regenerator.wrap(function(m){for(;;)switch(m.prev=m.next){case 0:case "end":return m.stop()}},g,this)}));return L.apply(this,arguments)}function N(){N=_asyncToGenerator(_regenerator.mark(function g(n,r){return _regenerator.wrap(function(m){for(;;)switch(m.prev=
m.next){case 0:case "end":return m.stop()}},g,this)}));return N.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function r(n){var g,m,h,u,e,k,f,p;return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return g=jQuery(n.parentNode).closest(".blck").first(),m=g.find(".url"),h=g.find(".messages"),u=g.find(".seraph_accel_spinner"),e=g.find('input[type="button"]'),k=0,g.find(".liteChk").prop("checked")&&(k|=1),g.find(".medChk").prop("checked")&&(k|=2),g.find(".tidyChk").prop("checked")&&
(k|=524288),h.empty(),u.show(),e.prop("disabled",!0),a.prev=12,a.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:m.val(),norm:k}),type:"POST",data:"",dataType:"json",cache:!1});case 15:f=a.sent;a.next=21;break;case 18:a.prev=18,a.t0=a["catch"](12),f={err:a.t0.statusText};case 21:u.hide();e.prop("disabled",!1);if(!f.err){a.next=26;break}h.append(seraph_accel.Ui.LogItem("error",f.err));return a.abrupt("return");case 26:for(p in f.list)p=
f.list[p],h.append(seraph_accel.Ui.LogItem(p.severity,p.text));case 27:case "end":return a.stop()}},r,this,[[12,18]])}));return O.apply(this,arguments)}var R=seraph_accel.Wp.Loc.GetApi(),C=R._x,E=R.sprintf;seraph_accel.Settings={_int:{OnUpdateCssAuto:function(t){seraph_accel.Ui.ComboShowDependedItems(t,jQuery(t.parentNode).closest(".blck").first().get(0))},OnLogClear:function(t){return w.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(t,n){return I.apply(this,arguments)},OnCacheOp:function(t,
n,r){return B.apply(this,arguments)},OnCacheOpCancel:function(t,n,r){return K.apply(this,arguments)},OnPostUpdCancel:function(t){return F.apply(this,arguments)},OnScheUpdCancel:function(t){return D.apply(this,arguments)},OnExtDbUpdBegin:function(t){return A.apply(this,arguments)},OnExtDbUpdCancel:function(t){return G.apply(this,arguments)},OnQueueDel:function(t,n,r){return P.apply(this,arguments)},OnQueuePause:function(t,n,r){return Q.apply(this,arguments)},OnQueueItemCancel:function(t,n,r){return M.apply(this,
arguments)},OnDataRefreshInit:function(t,n){return L.apply(this,arguments)},OnDataRefresh:function(t,n){return N.apply(this,arguments)},OnHtmlCheck:function(t){return O.apply(this,arguments)}}};(function(){function t(m){return n.apply(this,arguments)}function n(){n=_asyncToGenerator(_regenerator.mark(function u(h){var e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return e={},f.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"SelfDiag_"+h,{}),cache:!1,dataType:"json"}),f.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:e=f.sent;delete seraph_accel.SelfDiag._int.curAjax;f.next=14;break;case 9:f.prev=9,f.t0=f["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===f.t0.status?e.hr=seraph_accel.Gen.hr.S_ABORTED:(e.hr=seraph_accel.Gen.hr.E_FAIL,e.descr="HTTP "+f.t0.status),500==f.t0.status&&(k=document.implementation.createHTMLDocument(""),k.documentElement.innerHTML=f.t0.responseText,k=k.body.textContent,k=seraph_accel.Gen.StrReplaceAll(k,
"\r",""),k=seraph_accel.Gen.StrReplaceAll(k,["\t","\v"]," "),k=seraph_accel.Gen.StrReplaceAll(k,"\n",". "),(k=seraph_accel.Gen.StrReplaceAllWhileChanging(k,["  ",". . "],[" ",". "]).trim())&&"."!=k&&(e.descr+="<br>"+k));case 14:return f.abrupt("return",e);case 15:case "end":return f.stop()}},u,this,[[1,9]])}));return n.apply(this,arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function u(h){var e,k,f,p,a,b,c,l,d,q,x,z=arguments;return _regenerator.wrap(function(v){for(;;)switch(v.prev=
v.next){case 0:e=1<z.length&&void 0!==z[1]?z[1]:!1;k=jQuery(h.parentNode).closest(".blck").first();f=k.find(".seraph_accel_spinner");p=k.find('input[type="button"]:not(.cancel)');a=k.find('input[type="button"].cancel');b=k.find(".log");c=[{id:"3rdPartySettCompat",name:g("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:g("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:g("TestName_SetMaxExecTime","admin.SelfDiag",
"seraphinite-accelerator")},{id:"PageOptimize",name:g("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:g("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:g("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];b.empty();for(l=0;l<c.length;l++)d=c[l],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id),!1));if(!e){v.next=11;break}return v.abrupt("return");case 11:f.show(),p.prop("disabled",
!0),a.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,l=0;case 16:if(!(l<c.length)){v.next=31;break}d=c[l];jQuery(b.children().get(l)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id)+g("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));v.next=21;return t(d.id);case 21:q=v.sent;x=g("TestSucc","admin.SelfDiag","seraphinite-accelerator");q.hr!=seraph_accel.Gen.hr.S_OK&&(x=seraph_accel.Gen.hr.Succ(q.hr)?q.hr==seraph_accel.Gen.hr.S_ABORTED?
g("TestAbort","admin.SelfDiag","seraphinite-accelerator"):q.hr==seraph_accel.Gen.hr.S_FALSE?g("TestNotice","admin.SelfDiag","seraphinite-accelerator"):g("TestWarn","admin.SelfDiag","seraphinite-accelerator"):g("TestError","admin.SelfDiag","seraphinite-accelerator"));q.descr&&(x+="<br>"+q.descr);jQuery(b.children().get(l)).replaceWith(seraph_accel.Ui.LogItem(q.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(q.hr)?q.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",
d.name?d.name:d.id)+x,!1));if(seraph_accel.SelfDiag._int.inProgress){v.next=28;break}return v.abrupt("break",31);case 28:l++;v.next=16;break;case 31:f.hide(),p.prop("disabled",!1),a.prop("disabled",!0);case 34:case "end":return v.stop()}},u,this)}));return r.apply(this,arguments)}var g=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(m){return r.apply(this,arguments)},OnCancel:function(m){m=jQuery(m.parentNode).closest(".blck").first();m.find(".seraph_accel_spinner");
m.find('input[type="button"]:not(.cancel)');m.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
