function asyncGeneratorStep(B,y,K,J,H,F,C){try{var I=B[F](C),D=I.value}catch(L){K(L);return}I.done?y(D):Promise.resolve(D).then(J,H)}function _asyncToGenerator(B){return function(){var y=this,K=arguments;return new Promise(function(J,H){function F(D){asyncGeneratorStep(I,J,H,F,C,"next",D)}function C(D){asyncGeneratorStep(I,J,H,F,C,"throw",D)}var I=B.apply(y,K);F(void 0)})}}
function _typeof(B){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(y){return typeof y}:function(y){return y&&"function"===typeof Symbol&&y.constructor===Symbol&&y!==Symbol.prototype?"symbol":typeof y};return _typeof(B)}var _regenerator;
(function(){var B=function(y){function K(b,a,c,m){a=Object.create((a&&a.prototype instanceof H?a:H).prototype);m=new M(m||[]);a._invoke=L(b,c,m);return a}function J(b,a,c){try{return{type:"normal",arg:b.call(a,c)}}catch(m){return{type:"throw",arg:m}}}function H(){}function F(){}function C(){}function I(b){["next","throw","return"].forEach(function(a){b[a]=function(c){return this._invoke(a,c)}})}function D(b,a){function c(d,p,u,w){d=J(b[d],b,p);if("throw"===d.type)w(d.arg);else{var v=d.arg;return(d=
v.value)&&"object"===_typeof(d)&&E.call(d,"__await")?a.resolve(d.__await).then(function(A){c("next",A,u,w)},function(A){c("throw",A,u,w)}):a.resolve(d).then(function(A){v.value=A;u(v)},function(A){return c("throw",A,u,w)})}}var m;this._invoke=function(d,p){function u(){return new a(function(w,v){c(d,p,w,v)})}return m=m?m.then(u,u):u()}}function L(b,a,c){var m=l;return function(d,p){if(m===r)throw Error("Generator is already running");if(m===e){if("throw"===d)throw p;return P()}c.method=d;for(c.arg=
p;;){if(d=c.delegate)if(d=Q(d,c)){if(d===k)continue;return d}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(m===l)throw m=e,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);m=r;d=J(b,a,c);if("normal"===d.type){m=c.done?e:g;if(d.arg===k)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(m=e,c.method="throw",c.arg=d.arg)}}}function Q(b,a){var c=b.iterator[a.method];if(c===G){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=G,Q(b,a),"throw"===a.method))return k;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return k}c=J(c,b.iterator,a.arg);if("throw"===c.type)return a.method="throw",a.arg=c.arg,a.delegate=null,k;c=c.arg;if(!c)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,k;if(c.done)a[b.resultName]=c.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=G);else return c;a.delegate=null;return k}
function R(b){var a={tryLoc:b[0]};1 in b&&(a.catchLoc=b[1]);2 in b&&(a.finallyLoc=b[2],a.afterLoc=b[3]);this.tryEntries.push(a)}function N(b){var a=b.completion||{};a.type="normal";delete a.arg;b.completion=a}function M(b){this.tryEntries=[{tryLoc:"root"}];b.forEach(R,this);this.reset(!0)}function O(b){if(b){var a=b[q];if(a)return a.call(b);if("function"===typeof b.next)return b;if(!isNaN(b.length)){var c=-1;a=function d(){for(;++c<b.length;)if(E.call(b,c))return d.value=b[c],d.done=!1,d;d.value=
G;d.done=!0;return d};return a.next=a}}return{next:P}}function P(){return{value:G,done:!0}}var S=Object.prototype,E=S.hasOwnProperty,G,x="function"===typeof Symbol?Symbol:{},q=x.iterator||"@@iterator",t=x.asyncIterator||"@@asyncIterator",h=x.toStringTag||"@@toStringTag";y.wrap=K;var l="suspendedStart",g="suspendedYield",r="executing",e="completed",k={};x={};x[q]=function(){return this};var f=Object.getPrototypeOf;(f=f&&f(f(O([]))))&&f!==S&&E.call(f,q)&&(x=f);var n=C.prototype=H.prototype=Object.create(x);
F.prototype=n.constructor=C;C.constructor=F;C[h]=F.displayName="GeneratorFunction";y.isGeneratorFunction=function(b){return(b="function"===typeof b&&b.constructor)?b===F||"GeneratorFunction"===(b.displayName||b.name):!1};y.mark=function(b){Object.setPrototypeOf?Object.setPrototypeOf(b,C):(b.__proto__=C,h in b||(b[h]="GeneratorFunction"));b.prototype=Object.create(n);return b};y.awrap=function(b){return{__await:b}};I(D.prototype);D.prototype[t]=function(){return this};y.AsyncIterator=D;y.async=function(b,
a,c,m,d){void 0===d&&(d=Promise);var p=new D(K(b,a,c,m),d);return y.isGeneratorFunction(a)?p:p.next().then(function(u){return u.done?u.value:p.next()})};I(n);n[h]="Generator";n[q]=function(){return this};n.toString=function(){return"[object Generator]"};y.keys=function(b){var a=[],c;for(c in b)a.push(c);a.reverse();return function d(){for(;a.length;){var p=a.pop();if(p in b)return d.value=p,d.done=!1,d}d.done=!0;return d}};y.values=O;M.prototype={constructor:M,reset:function(b){this.next=this.prev=
0;this.sent=this._sent=G;this.done=!1;this.delegate=null;this.method="next";this.arg=G;this.tryEntries.forEach(N);if(!b)for(var a in this)"t"===a.charAt(0)&&E.call(this,a)&&!isNaN(+a.slice(1))&&(this[a]=G)},stop:function(){this.done=!0;var b=this.tryEntries[0].completion;if("throw"===b.type)throw b.arg;return this.rval},dispatchException:function(b){function a(v,A){p.type="throw";p.arg=b;c.next=v;A&&(c.method="next",c.arg=G);return!!A}if(this.done)throw b;for(var c=this,m=this.tryEntries.length-1;0<=
m;--m){var d=this.tryEntries[m],p=d.completion;if("root"===d.tryLoc)return a("end");if(d.tryLoc<=this.prev){var u=E.call(d,"catchLoc"),w=E.call(d,"finallyLoc");if(u&&w){if(this.prev<d.catchLoc)return a(d.catchLoc,!0);if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else if(u){if(this.prev<d.catchLoc)return a(d.catchLoc,!0)}else if(w){if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(b,a){for(var c=this.tryEntries.length-
1;0<=c;--c){var m=this.tryEntries[c];if(m.tryLoc<=this.prev&&E.call(m,"finallyLoc")&&this.prev<m.finallyLoc){var d=m;break}}d&&("break"===b||"continue"===b)&&d.tryLoc<=a&&a<=d.finallyLoc&&(d=null);c=d?d.completion:{};c.type=b;c.arg=a;return d?(this.method="next",this.next=d.finallyLoc,k):this.complete(c)},complete:function(b,a){if("throw"===b.type)throw b.arg;"break"===b.type||"continue"===b.type?this.next=b.arg:"return"===b.type?(this.rval=this.arg=b.arg,this.method="return",this.next="end"):"normal"===
b.type&&a&&(this.next=a);return k},finish:function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.finallyLoc===b)return this.complete(c.completion,c.afterLoc),N(c),k}},"catch":function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.tryLoc===b){b=c.completion;if("throw"===b.type){var m=b.arg;N(c)}return m}}throw Error("illegal catch attempt");},delegateYield:function(b,a,c){this.delegate={iterator:O(b),resultName:a,nextLoc:c};"next"===this.method&&
(this.arg=G);return k}};return y}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=B}catch(y){Function("r","_regenerator = r")(B)}})();
(function(){function B(x){var q=null;x==seraph_accel.Gen.hr.E_CONTEXT_EXPIRED?q=E("OpSrvCtxExpired","admin.Manage","seraphinite-accelerator"):seraph_accel.Gen.hr.Fail(x)&&(q=G(E("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),x));return q}function y(){y=_asyncToGenerator(_regenerator.mark(function t(q){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return jQuery(q).attr("disabled",!0),h.prev=1,h.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:h.next=8;break;case 6:h.prev=6,h.t0=h["catch"](1);case 8:jQuery(q).attr("disabled",!1);case 9:case "end":return h.stop()}},t,this,[[1,6]])}));return y.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function h(q,t){var l,g,r,e,k,f;return _regenerator.wrap(function(n){for(;;)switch(n.prev=n.next){case 0:l=jQuery(q.parentNode).closest(".blck").first();g=l.find(".seraph_accel_spinner");l.find(".content");r=
l.find('input[type="button"]:not(.cancel)');e=l.find('input[type="button"].cancel');if(!t){n.next=23;break}r.prop("disabled",!0);g.show();seraph_accel.Manager._int.notRefreshStat=!0;k=null;n.prev=10;n.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:f=n.sent;seraph_accel.Gen.hr.Fail(f)&&(k=G(E("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),f));n.next=20;break;case 17:n.prev=17,
n.t0=n["catch"](10),k="HTTP "+n.t0.status;case 20:return k&&(alert(k),r.prop("disabled",!1),g.hide()),delete seraph_accel.Manager._int.notRefreshStat,n.abrupt("return");case 23:return e.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,k=null,n.prev=26,n.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:f=n.sent;k=B(f);n.next=37;break;case 33:n.prev=33,n.t1=n["catch"](26),
k="HTTP "+n.t1.status,e.prop("disabled",!1);case 37:k&&alert(k),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return n.stop()}},h,this,[[10,17],[26,33]])}));return K.apply(this,arguments)}function J(x){switch(x){case 0:return E("OpDescr_Invalidate","admin.Manage","seraphinite-accelerator");case 3:return E("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return E("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return E("OpDescr_SrvDel",
"admin.Manage","seraphinite-accelerator")}return""+x}function H(){H=_asyncToGenerator(_regenerator.mark(function t(q){var h,l,g,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return h=jQuery(q.parentNode).closest(".blck").first(),l=h.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=
e.sent;g=B(r);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},t,this,[[4,11]])}));return H.apply(this,arguments)}function F(){F=_asyncToGenerator(_regenerator.mark(function t(q){var h,l,g,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return h=jQuery(q.parentNode).closest(".blck").first(),l=h.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;g=B(r);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},t,this,[[4,11]])}));return F.apply(this,arguments)}function C(){C=_asyncToGenerator(_regenerator.mark(function t(q){var h,l,g,r,e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return h=jQuery(q.parentNode).closest(".blck").first(),l=h.find(".seraph_accel_spinner"),
g=h.find('input[type="button"]:not(.cancel)'),r=h.find('input[type="button"].cancel'),l.show(),g.prop("disabled",!0),r.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,e=null,f.prev=9,f.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:k=f.sent;e=B(k);f.next=19;break;case 16:f.prev=16,f.t0=f["catch"](9),e="HTTP "+f.t0.status;case 19:e&&alert(e),delete seraph_accel.Manager._int.notRefreshExtDp;
case 21:case "end":return f.stop()}},t,this,[[9,16]])}));return C.apply(this,arguments)}function I(){I=_asyncToGenerator(_regenerator.mark(function t(q){var h,l,g,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return h=jQuery(q.parentNode).closest(".blck").first(),l=h.find('input[type="button"].cancel'),l.prop("disabled",!0),g=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdCancel",{}),type:"POST",data:"",
cache:!1,dataType:"json"});case 7:r=e.sent;g=B(r);e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),g="HTTP "+e.t0.status;case 14:g&&alert(g);case 15:case "end":return e.stop()}},t,this,[[4,11]])}));return I.apply(this,arguments)}function D(){D=_asyncToGenerator(_regenerator.mark(function l(q,t,h){var g,r,e,k,f,n,b,a,c,m,d,p,u,w,v,A;return _regenerator.wrap(function(z){for(;;)switch(z.prev=z.next){case 0:return g=jQuery(q.parentNode).closest(".blck").first(),r=g.find(".seraph_accel_spinner"),e=
g.find(".descr"),k=g.find('input[type="button"]:not(.cancel)'),f=g.find('input[type="button"].cancel'),n=g.find("#seraph_accel_views"),b=g.find("#seraph_accel_geos"),a=g.find("#seraph_accel_langs"),c=[],n.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(n.get()),c=seraph_accel.Ui.TokensList.GetVal(n.get())),m=[],b.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(b.get()),m=seraph_accel.Ui.TokensList.GetVal(b.get()).filter(function(T){return"_"!==T})),d=[],a.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(a.get()),
d=seraph_accel.Ui.TokensList.GetVal(a.get())),u=String(g.find(".type").val()),"uri"===u?p=g.find(".uri").val():0===u.indexOf("uri:")&&(p=u.substr(4),u="uri"),p="string"==typeof p?seraph_accel.Gen.StrReplaceAll(p,["\r","\n","*"],["",";","{ASTRSK}"]):"",r.show(),e.show(),e.text(J(t)),k.prop("disabled",!0),f.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,w={cache:!1,dataType:"json"},512>p.length?w.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",
{type:u,op:t,uri:p,v:c.join(),g:m.length?m.join():void 0,l:d.length?d.join():void 0,_wpnonce:h}):(w.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:u,op:t,v:c.join(),g:m.length?m.join():void 0,l:d.length?d.join():void 0,_wpnonce:h}),w.type="POST",w.contentType="application/x-www-form-urlencoded",w.data="uri="+encodeURIComponent(p)),v=null,z.prev=26,z.next=29,jQuery.ajax(w);case 29:A=z.sent;v=B(A);z.next=36;break;case 33:z.prev=33,z.t0=z["catch"](26),
v="HTTP "+z.t0.status;case 36:v&&alert(v),delete seraph_accel.Manager._int.notRefreshOp;case 38:case "end":return z.stop()}},l,this,[[26,33]])}));return D.apply(this,arguments)}function L(){L=_asyncToGenerator(_regenerator.mark(function l(q,t,h){var g,r,e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return g=jQuery(q.parentNode).closest(".blck").first(),r=g.find('input[type="button"].cancel'),r.prop("disabled",!0),e=null,f.prev=4,f.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpCancel",{op:t,_wpnonce:h}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:k=f.sent;e=B(k);f.next=14;break;case 11:f.prev=11,f.t0=f["catch"](4),e="HTTP "+f.t0.status;case 14:e&&alert(e);case 15:case "end":return f.stop()}},l,this,[[4,11]])}));return L.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function l(q,t,h){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:case "end":return g.stop()}},l,this)}));return Q.apply(this,arguments)}
function R(){R=_asyncToGenerator(_regenerator.mark(function l(q,t,h){return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:case "end":return g.stop()}},l,this)}));return R.apply(this,arguments)}function N(){N=_asyncToGenerator(_regenerator.mark(function g(q,t,h,l){return _regenerator.wrap(function(r){for(;;)switch(r.prev=r.next){case 0:case "end":return r.stop()}},g,this)}));return N.apply(this,arguments)}function M(){M=_asyncToGenerator(_regenerator.mark(function h(q,t){var l,
g,r,e;return _regenerator.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:e=function(){e=_asyncToGenerator(_regenerator.mark(function n(){return _regenerator.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return b.next=2,seraph_accel.Manager._int.OnDataRefresh(q,t);case 2:g();case 3:case "end":return b.stop()}},n,this)}));return e.apply(this,arguments)},r=function(){return e.apply(this,arguments)},g=function(){var f=1E3*parseInt(l.val(),10);100>f&&(f=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);
seraph_accel.Manager._int.refreshTimer=setTimeout(r,f)},l=jQuery("#seraph_accel_manage .tmDataRefresh"),l.on("change",g),r();case 6:case "end":return k.stop()}},h,this)}));return M.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function h(q,t){var l,g,r,e,k,f,n,b,a,c,m,d,p,u,w,v,A;return _regenerator.wrap(function(z){for(;;)switch(z.prev=z.next){case 0:return l=jQuery(q).find("#status").first(),g=jQuery(q).find("#stat").first(),r=g.find(".seraph_accel_spinner"),e=g.find('input[type="button"]:not(.cancel)'),
k=g.find('input[type="button"].cancel'),f=jQuery(q).find("#operate").first(),n=f.find(".seraph_accel_spinner"),b=f.find(".descr"),a=f.find('input[type="button"]:not(.cancel)'),c=f.find('input[type="button"].cancel'),m=jQuery(q).find("#queue").first(),m.find(".content"),d=m.find(".maxItems"),m.find(".seraph_accel_spinner"),m.find('input[type="button"]'),m.find(".descrNums"),z.prev=16,z.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",{nMaxQueueItems:d.val(),
allSites:t?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:v=z.sent;z.next=24;break;case 22:z.prev=22,z.t0=z["catch"](16);case 24:if(v){z.next=26;break}return z.abrupt("return");case 26:if(!t){for(A in v.status.cont)l.find('[data-id-cont="'+A+'"]').html(v.status.cont[A]);seraph_accel.Manager._int.notRefreshPostUpd||(p=l.find(".blck.postupd .seraph_accel_spinner"),u=l.find('.blck.postupd input[type="button"]:not(.cancel)'),w=l.find('.blck.postupd input[type="button"].cancel'),v.status.postUpd?
(p.show(),u.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),u.prop("disabled",!1),w.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(p=l.find(".blck.scheupd .seraph_accel_spinner"),u=l.find('.blck.scheupd input[type="button"]:not(.cancel)'),w=l.find('.blck.scheupd input[type="button"].cancel'),v.status.scheUpd?(p.show(),u.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),u.prop("disabled",!1),w.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||(p=l.find(".blck.cleanup .seraph_accel_spinner"),
u=l.find('.blck.cleanup input[type="button"]:not(.cancel)'),w=l.find('.blck.cleanup input[type="button"].cancel'),v.status.cleanUp?(p.show(),u.prop("disabled",!0),w.prop("disabled",!1)):(p.hide(),u.prop("disabled",!1),w.prop("disabled",!0)))}t||seraph_accel.Manager._int.notRefreshExtDp||(p=l.find(".blck.extdb .seraph_accel_spinner"),u=l.find('.blck.extdb input[type="button"]:not(.cancel)'),w=l.find('.blck.extdb input[type="button"].cancel'),v.extDb.isUpdating?(p.show(),u.prop("disabled",!0),w.prop("disabled",
!1)):(p.hide(),u.prop("disabled",!1),w.prop("disabled",!0)));t||seraph_accel.Manager._int.notRefreshStat||(v.stat.isUpdating?(r.show(),e.prop("disabled",!0),k.prop("disabled",!1)):(r.hide(),e.prop("disabled",!1),k.prop("disabled",!0)),g.find('[data-id-cont="stat"]').html(v.stat.cont));t||seraph_accel.Manager._int.notRefreshOp||(null===v.curOp&&(v.curOp=void 0),void 0!==v.curOp?(n.show(),b.show(),b.text(J(v.curOp)),a.prop("disabled",!0),c.prop("disabled",!1)):(n.hide(),b.hide(),a.prop("disabled",!1),
c.prop("disabled",!0),b.text("")));case 30:case "end":return z.stop()}},h,this,[[16,22]])}));return O.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function t(q){var h,l,g,r,e,k,f,n,b;return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return h=jQuery(q.parentNode).closest(".blck").first(),l=h.find(".url"),g=h.find(".seraph_accel_spinner"),r=h.find('input[type="button"]'),e=h.find(".messages"),k=h.find(".info"),f=0,h.find(".liteChk").prop("checked")&&
(f|=1),h.find(".medChk").prop("checked")&&(f|=2),h.find(".tidyChk").prop("checked")&&(f|=524288),e.empty(),g.show(),r.prop("disabled",!0),a.prev=13,a.next=16,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:l.val(),norm:f}),type:"POST",data:"",dataType:"json",cache:!1});case 16:n=a.sent;a.next=22;break;case 19:a.prev=19,a.t0=a["catch"](13),n={err:a.t0.statusText};case 22:g.hide();r.prop("disabled",!1);if(!n.err){a.next=27;break}e.append(seraph_accel.Ui.LogItem("error",
n.err));return a.abrupt("return");case 27:for(b in k.html(n.info),n.list)b=n.list[b],e.append(seraph_accel.Ui.LogItem(b.severity,b.text));case 29:case "end":return a.stop()}},t,this,[[13,19]])}));return P.apply(this,arguments)}var S=seraph_accel.Wp.Loc.GetApi(),E=S._x,G=S.sprintf;seraph_accel.Settings={_int:{OnUpdateCssAuto:function(x){seraph_accel.Ui.ComboShowDependedItems(x,jQuery(x.parentNode).closest(".blck").first().get(0))},OnLogClear:function(x){return y.apply(this,arguments)}}};seraph_accel.Manager=
{_int:{OnStatOp:function(x,q){return K.apply(this,arguments)},OnCacheOp:function(x,q,t){return D.apply(this,arguments)},OnCacheOpCancel:function(x,q,t){return L.apply(this,arguments)},OnPostUpdCancel:function(x){return H.apply(this,arguments)},OnScheUpdCancel:function(x){return F.apply(this,arguments)},OnExtDbUpdBegin:function(x){return C.apply(this,arguments)},OnExtDbUpdCancel:function(x){return I.apply(this,arguments)},OnQueueDel:function(x,q,t){return Q.apply(this,arguments)},OnQueuePause:function(x,
q,t){return R.apply(this,arguments)},OnQueueItemCancel:function(x,q,t,h){return N.apply(this,arguments)},OnDataRefreshInit:function(x,q){return M.apply(this,arguments)},OnDataRefresh:function(x,q){return O.apply(this,arguments)},OnHtmlCheck:function(x){return P.apply(this,arguments)}}};(function(){function x(l){return q.apply(this,arguments)}function q(){q=_asyncToGenerator(_regenerator.mark(function r(g){var e,k;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return e={},
f.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+g,{}),cache:!1,dataType:"json"}),f.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:e=f.sent;delete seraph_accel.SelfDiag._int.curAjax;f.next=14;break;case 9:f.prev=9,f.t0=f["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===f.t0.status?e.hr=seraph_accel.Gen.hr.S_ABORTED:(e.hr=seraph_accel.Gen.hr.E_FAIL,e.descr="HTTP "+f.t0.status),500==f.t0.status&&
(k=document.implementation.createHTMLDocument(""),k.documentElement.innerHTML=f.t0.responseText,k=k.body.textContent,k=seraph_accel.Gen.StrReplaceAll(k,"\r",""),k=seraph_accel.Gen.StrReplaceAll(k,["\t","\v"]," "),k=seraph_accel.Gen.StrReplaceAll(k,"\n",". "),(k=seraph_accel.Gen.StrReplaceAllWhileChanging(k,["  ",". . "],[" ",". "]).trim())&&"."!=k&&(e.descr+="<br>"+k));case 14:return f.abrupt("return",e);case 15:case "end":return f.stop()}},r,this,[[1,9]])}));return q.apply(this,arguments)}function t(){t=
_asyncToGenerator(_regenerator.mark(function r(g){var e,k,f,n,b,a,c,m,d,p,u,w=arguments;return _regenerator.wrap(function(v){for(;;)switch(v.prev=v.next){case 0:e=1<w.length&&void 0!==w[1]?w[1]:!1;k=jQuery(g.parentNode).closest(".blck").first();f=k.find(".seraph_accel_spinner");n=k.find('input[type="button"]:not(.cancel)');b=k.find('input[type="button"].cancel');a=k.find(".log");c=[{id:"3rdPartySettCompat",name:h("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",
name:h("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:h("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:h("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:h("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:h("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];a.empty();for(m=0;m<c.length;m++)d=c[m],a.append(seraph_accel.Ui.LogItem("none",
seraph_accel.Ui.Tag("strong",d.name?d.name:d.id),!1));if(!e){v.next=11;break}return v.abrupt("return");case 11:f.show(),n.prop("disabled",!0),b.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,m=0;case 16:if(!(m<c.length)){v.next=31;break}d=c[m];jQuery(a.children().get(m)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id)+h("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));v.next=21;return x(d.id);case 21:p=v.sent;u=h("TestSucc","admin.SelfDiag",
"seraphinite-accelerator");p.hr!=seraph_accel.Gen.hr.S_OK&&(u=seraph_accel.Gen.hr.Succ(p.hr)?p.hr==seraph_accel.Gen.hr.S_ABORTED?h("TestAbort","admin.SelfDiag","seraphinite-accelerator"):p.hr==seraph_accel.Gen.hr.S_FALSE?h("TestNotice","admin.SelfDiag","seraphinite-accelerator"):h("TestWarn","admin.SelfDiag","seraphinite-accelerator"):h("TestError","admin.SelfDiag","seraphinite-accelerator"));p.descr&&(u+="<br>"+p.descr);jQuery(a.children().get(m)).replaceWith(seraph_accel.Ui.LogItem(p.hr==seraph_accel.Gen.hr.S_OK?
"success":seraph_accel.Gen.hr.Succ(p.hr)?p.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",d.name?d.name:d.id)+u,!1));if(seraph_accel.SelfDiag._int.inProgress){v.next=28;break}return v.abrupt("break",31);case 28:m++;v.next=16;break;case 31:f.hide(),n.prop("disabled",!1),b.prop("disabled",!0);case 34:case "end":return v.stop()}},r,this)}));return t.apply(this,arguments)}var h=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(l){return t.apply(this,
arguments)},OnCancel:function(l){l=jQuery(l.parentNode).closest(".blck").first();l.find(".seraph_accel_spinner");l.find('input[type="button"]:not(.cancel)');l.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
