function asyncGeneratorStep(D,w,K,E,F,C,z){try{var G=D[C](z),A=G.value}catch(L){K(L);return}G.done?w(A):Promise.resolve(A).then(E,F)}function _asyncToGenerator(D){return function(){var w=this,K=arguments;return new Promise(function(E,F){function C(A){asyncGeneratorStep(G,E,F,C,z,"next",A)}function z(A){asyncGeneratorStep(G,E,F,C,z,"throw",A)}var G=D.apply(w,K);C(void 0)})}}
function _typeof(D){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(w){return typeof w}:function(w){return w&&"function"===typeof Symbol&&w.constructor===Symbol&&w!==Symbol.prototype?"symbol":typeof w};return _typeof(D)}var _regenerator;
(function(){var D=function(w){function K(b,a,c,n){a=Object.create((a&&a.prototype instanceof F?a:F).prototype);n=new M(n||[]);a._invoke=L(b,c,n);return a}function E(b,a,c){try{return{type:"normal",arg:b.call(a,c)}}catch(n){return{type:"throw",arg:n}}}function F(){}function C(){}function z(){}function G(b){["next","throw","return"].forEach(function(a){b[a]=function(c){return this._invoke(a,c)}})}function A(b,a){function c(d,u,x,J){d=E(b[d],b,u);if("throw"===d.type)J(d.arg);else{var N=d.arg;return(d=
N.value)&&"object"===_typeof(d)&&t.call(d,"__await")?a.resolve(d.__await).then(function(I){c("next",I,x,J)},function(I){c("throw",I,x,J)}):a.resolve(d).then(function(I){N.value=I;x(N)},function(I){return c("throw",I,x,J)})}}var n;this._invoke=function(d,u){function x(){return new a(function(J,N){c(d,u,J,N)})}return n=n?n.then(x,x):x()}}function L(b,a,c){var n=r;return function(d,u){if(n===g)throw Error("Generator is already running");if(n===l){if("throw"===d)throw u;return B()}c.method=d;for(c.arg=
u;;){if(d=c.delegate)if(d=P(d,c)){if(d===m)continue;return d}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(n===r)throw n=l,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);n=g;d=E(b,a,c);if("normal"===d.type){n=c.done?l:e;if(d.arg===m)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(n=l,c.method="throw",c.arg=d.arg)}}}function P(b,a){var c=b.iterator[a.method];if(c===p){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=p,P(b,a),"throw"===a.method))return m;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return m}c=E(c,b.iterator,a.arg);if("throw"===c.type)return a.method="throw",a.arg=c.arg,a.delegate=null,m;c=c.arg;if(!c)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,m;if(c.done)a[b.resultName]=c.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=p);else return c;a.delegate=null;return m}
function R(b){var a={tryLoc:b[0]};1 in b&&(a.catchLoc=b[1]);2 in b&&(a.finallyLoc=b[2],a.afterLoc=b[3]);this.tryEntries.push(a)}function O(b){var a=b.completion||{};a.type="normal";delete a.arg;b.completion=a}function M(b){this.tryEntries=[{tryLoc:"root"}];b.forEach(R,this);this.reset(!0)}function Q(b){if(b){var a=b[f];if(a)return a.call(b);if("function"===typeof b.next)return b;if(!isNaN(b.length)){var c=-1;a=function d(){for(;++c<b.length;)if(t.call(b,c))return d.value=b[c],d.done=!1,d;d.value=
p;d.done=!0;return d};return a.next=a}}return{next:B}}function B(){return{value:p,done:!0}}var H=Object.prototype,t=H.hasOwnProperty,p,q="function"===typeof Symbol?Symbol:{},f=q.iterator||"@@iterator",h=q.asyncIterator||"@@asyncIterator",k=q.toStringTag||"@@toStringTag";w.wrap=K;var r="suspendedStart",e="suspendedYield",g="executing",l="completed",m={};q={};q[f]=function(){return this};var v=Object.getPrototypeOf;(v=v&&v(v(Q([]))))&&v!==H&&t.call(v,f)&&(q=v);var y=z.prototype=F.prototype=Object.create(q);
C.prototype=y.constructor=z;z.constructor=C;z[k]=C.displayName="GeneratorFunction";w.isGeneratorFunction=function(b){return(b="function"===typeof b&&b.constructor)?b===C||"GeneratorFunction"===(b.displayName||b.name):!1};w.mark=function(b){Object.setPrototypeOf?Object.setPrototypeOf(b,z):(b.__proto__=z,k in b||(b[k]="GeneratorFunction"));b.prototype=Object.create(y);return b};w.awrap=function(b){return{__await:b}};G(A.prototype);A.prototype[h]=function(){return this};w.AsyncIterator=A;w.async=function(b,
a,c,n,d){void 0===d&&(d=Promise);var u=new A(K(b,a,c,n),d);return w.isGeneratorFunction(a)?u:u.next().then(function(x){return x.done?x.value:u.next()})};G(y);y[k]="Generator";y[f]=function(){return this};y.toString=function(){return"[object Generator]"};w.keys=function(b){var a=[],c;for(c in b)a.push(c);a.reverse();return function d(){for(;a.length;){var u=a.pop();if(u in b)return d.value=u,d.done=!1,d}d.done=!0;return d}};w.values=Q;M.prototype={constructor:M,reset:function(b){this.next=this.prev=
0;this.sent=this._sent=p;this.done=!1;this.delegate=null;this.method="next";this.arg=p;this.tryEntries.forEach(O);if(!b)for(var a in this)"t"===a.charAt(0)&&t.call(this,a)&&!isNaN(+a.slice(1))&&(this[a]=p)},stop:function(){this.done=!0;var b=this.tryEntries[0].completion;if("throw"===b.type)throw b.arg;return this.rval},dispatchException:function(b){function a(N,I){u.type="throw";u.arg=b;c.next=N;I&&(c.method="next",c.arg=p);return!!I}if(this.done)throw b;for(var c=this,n=this.tryEntries.length-1;0<=
n;--n){var d=this.tryEntries[n],u=d.completion;if("root"===d.tryLoc)return a("end");if(d.tryLoc<=this.prev){var x=t.call(d,"catchLoc"),J=t.call(d,"finallyLoc");if(x&&J){if(this.prev<d.catchLoc)return a(d.catchLoc,!0);if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else if(x){if(this.prev<d.catchLoc)return a(d.catchLoc,!0)}else if(J){if(this.prev<d.finallyLoc)return a(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(b,a){for(var c=this.tryEntries.length-
1;0<=c;--c){var n=this.tryEntries[c];if(n.tryLoc<=this.prev&&t.call(n,"finallyLoc")&&this.prev<n.finallyLoc){var d=n;break}}d&&("break"===b||"continue"===b)&&d.tryLoc<=a&&a<=d.finallyLoc&&(d=null);c=d?d.completion:{};c.type=b;c.arg=a;return d?(this.method="next",this.next=d.finallyLoc,m):this.complete(c)},complete:function(b,a){if("throw"===b.type)throw b.arg;"break"===b.type||"continue"===b.type?this.next=b.arg:"return"===b.type?(this.rval=this.arg=b.arg,this.method="return",this.next="end"):"normal"===
b.type&&a&&(this.next=a);return m},finish:function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.finallyLoc===b)return this.complete(c.completion,c.afterLoc),O(c),m}},"catch":function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.tryLoc===b){b=c.completion;if("throw"===b.type){var n=b.arg;O(c)}return n}}throw Error("illegal catch attempt");},delegateYield:function(b,a,c){this.delegate={iterator:Q(b),resultName:a,nextLoc:c};"next"===this.method&&
(this.arg=p);return m}};return w}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=D}catch(w){Function("r","_regenerator = r")(D)}})();
(function(){function D(){D=_asyncToGenerator(_regenerator.mark(function q(p){return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return jQuery(p).attr("disabled",!0),f.prev=1,f.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:f.next=8;break;case 6:f.prev=6,f.t0=f["catch"](1);case 8:jQuery(p).attr("disabled",!1);case 9:case "end":return f.stop()}},q,this,[[1,6]])}));
return D.apply(this,arguments)}function w(){w=_asyncToGenerator(_regenerator.mark(function f(p,q){var h,k,r,e,g,l;return _regenerator.wrap(function(m){for(;;)switch(m.prev=m.next){case 0:h=jQuery(p.parentNode).closest(".blck").first();k=h.find(".seraph_accel_spinner");h.find(".content");r=h.find('input[type="button"]:not(.cancel)');e=h.find('input[type="button"].cancel');if(!q){m.next=23;break}r.prop("disabled",!0);k.show();seraph_accel.Manager._int.notRefreshStat=!0;g=null;m.prev=10;m.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:l=m.sent;seraph_accel.Gen.hr.Fail(l)&&(g=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),l));m.next=20;break;case 17:m.prev=17,m.t0=m["catch"](10),g="HTTP "+m.t0.status;case 20:return g&&(alert(g),r.prop("disabled",!1),k.hide()),delete seraph_accel.Manager._int.notRefreshStat,m.abrupt("return");case 23:return e.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,g=null,m.prev=26,m.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:l=m.sent;seraph_accel.Gen.hr.Fail(l)&&(g=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),l));m.next=37;break;case 33:m.prev=33,m.t1=m["catch"](26),g="HTTP "+m.t1.status,e.prop("disabled",!1);case 37:g&&alert(g),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return m.stop()}},f,this,[[10,17],[26,33]])}));return w.apply(this,arguments)}function K(t){switch(t){case 0:return B("OpDescr_Invalidate",
"admin.Manage","seraphinite-accelerator");case 3:return B("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return B("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return B("OpDescr_SrvDel","admin.Manage","seraphinite-accelerator")}return""+t}function E(){E=_asyncToGenerator(_regenerator.mark(function q(p){var f,h,k,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(p.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),
h.prop("disabled",!0),k=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(k=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),k="HTTP "+e.t0.status;case 14:k&&alert(k);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return E.apply(this,arguments)}function F(){F=
_asyncToGenerator(_regenerator.mark(function q(p){var f,h,k,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(p.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),h.prop("disabled",!0),k=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(k=H(B("OpSrvErr_%1$08X",
"admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),k="HTTP "+e.t0.status;case 14:k&&alert(k);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return F.apply(this,arguments)}function C(){C=_asyncToGenerator(_regenerator.mark(function q(p){var f,h,k,r,e,g;return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return f=jQuery(p.parentNode).closest(".blck").first(),h=f.find(".seraph_accel_spinner"),k=f.find('input[type="button"]:not(.cancel)'),
r=f.find('input[type="button"].cancel'),h.show(),k.prop("disabled",!0),r.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,e=null,l.prev=9,l.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:g=l.sent;seraph_accel.Gen.hr.Fail(g)&&(e=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));l.next=19;break;case 16:l.prev=16,l.t0=l["catch"](9),e="HTTP "+l.t0.status;
case 19:e&&alert(e),delete seraph_accel.Manager._int.notRefreshExtDp;case 21:case "end":return l.stop()}},q,this,[[9,16]])}));return C.apply(this,arguments)}function z(){z=_asyncToGenerator(_regenerator.mark(function q(p){var f,h,k,r;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return f=jQuery(p.parentNode).closest(".blck").first(),h=f.find('input[type="button"].cancel'),h.prop("disabled",!0),k=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ExtDbUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:r=e.sent;seraph_accel.Gen.hr.Fail(r)&&(k=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),r));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),k="HTTP "+e.t0.status;case 14:k&&alert(k);case 15:case "end":return e.stop()}},q,this,[[4,11]])}));return z.apply(this,arguments)}function G(){G=_asyncToGenerator(_regenerator.mark(function f(p,q){var h,k,r,e,g,l,m,v,y,b,a,c,n,d;return _regenerator.wrap(function(u){for(;;)switch(u.prev=
u.next){case 0:return h=jQuery(p.parentNode).closest(".blck").first(),k=h.find(".seraph_accel_spinner"),r=h.find(".descr"),e=h.find('input[type="button"]:not(.cancel)'),g=h.find('input[type="button"].cancel'),l=h.find("#seraph_accel_views"),m=h.find("#seraph_accel_geos"),v=[],l.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(l.get()),v=seraph_accel.Ui.TokensList.GetVal(l.get())),y=[],m.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(m.get()),y=seraph_accel.Ui.TokensList.GetVal(m.get())),a=String(h.find(".type").val()),
"uri"===a?b=h.find(".uri").val():0===a.indexOf("uri:")&&(b=a.substr(4),a="uri"),b=seraph_accel.Gen.StrReplaceAll(String(b),["\r","\n","*"],["",";","{ASTRSK}"]),k.show(),r.show(),r.text(K(q)),e.prop("disabled",!0),g.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,c={cache:!1,dataType:"json"},512>b.length?c.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:a,op:q,uri:b,v:v.join(),g:y.length?y.join():void 0}):(c.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpBegin",{type:a,op:q,v:v.join(),g:y.length?y.join():void 0}),c.type="POST",c.contentType="application/x-www-form-urlencoded",c.data="uri="+encodeURIComponent(b)),n=null,u.prev=23,u.next=26,jQuery.ajax(c);case 26:d=u.sent;seraph_accel.Gen.hr.Fail(d)&&(n=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),d));u.next=33;break;case 30:u.prev=30,u.t0=u["catch"](23),n="HTTP "+u.t0.status;case 33:n&&alert(n),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return u.stop()}},
f,this,[[23,30]])}));return G.apply(this,arguments)}function A(){A=_asyncToGenerator(_regenerator.mark(function f(p,q){var h,k,r,e;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return h=jQuery(p.parentNode).closest(".blck").first(),k=h.find('input[type="button"].cancel'),k.prop("disabled",!0),r=null,g.prev=4,g.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:q}),type:"POST",data:"",cache:!1,dataType:"json"});
case 7:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(r=H(B("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=14;break;case 11:g.prev=11,g.t0=g["catch"](4),r="HTTP "+g.t0.status;case 14:r&&alert(r);case 15:case "end":return g.stop()}},f,this,[[4,11]])}));return A.apply(this,arguments)}function L(){L=_asyncToGenerator(_regenerator.mark(function h(p,q,f){return _regenerator.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:case "end":return k.stop()}},h,this)}));return L.apply(this,
arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function h(p,q,f){return _regenerator.wrap(function(k){for(;;)switch(k.prev=k.next){case 0:case "end":return k.stop()}},h,this)}));return P.apply(this,arguments)}function R(){R=_asyncToGenerator(_regenerator.mark(function f(p,q){return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:case "end":return h.stop()}},f,this)}));return R.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function f(p,q){return _regenerator.wrap(function(h){for(;;)switch(h.prev=
h.next){case 0:case "end":return h.stop()}},f,this)}));return O.apply(this,arguments)}function M(){M=_asyncToGenerator(_regenerator.mark(function q(p){var f,h,k,r,e,g,l,m;return _regenerator.wrap(function(v){for(;;)switch(v.prev=v.next){case 0:return f=jQuery(p.parentNode).closest(".blck").first(),h=f.find(".url"),k=f.find(".messages"),r=f.find(".seraph_accel_spinner"),e=f.find('input[type="button"]'),g=0,f.find(".liteChk").prop("checked")&&(g|=1),f.find(".medChk").prop("checked")&&(g|=2),f.find(".tidyChk").prop("checked")&&
(g|=524288),k.empty(),r.show(),e.prop("disabled",!0),v.prev=12,v.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:h.val(),norm:g}),type:"POST",data:"",dataType:"json",cache:!1});case 15:l=v.sent;v.next=21;break;case 18:v.prev=18,v.t0=v["catch"](12),l={err:v.t0.statusText};case 21:r.hide();e.prop("disabled",!1);if(!l.err){v.next=26;break}k.append(seraph_accel.Ui.LogItem("error",l.err));return v.abrupt("return");case 26:for(m in l.list)m=
l.list[m],k.append(seraph_accel.Ui.LogItem(m.severity,m.text));case 27:case "end":return v.stop()}},q,this,[[12,18]])}));return M.apply(this,arguments)}var Q=seraph_accel.Wp.Loc.GetApi(),B=Q._x,H=Q.sprintf;seraph_accel.Settings={_int:{StrItem_OnAdd:function(t){function p(k){(k=k.trim())&&seraph_accel.Ui.TokensList.AddItem(h[0],k)}var q=1<arguments.length&&void 0!==arguments[1]?arguments[1]:",",f=jQuery(t.parentNode).closest(".blck").first(),h=f.find(".vals");f=f.find(".val");q?f.val().split(q).forEach(p):
p(f.val());f.val("")},StrItem_OnCopyAll:function(t){seraph_accel.Ui.TokensList.CopyAllItems(jQuery(t.parentNode).closest(".blck").first().find(".vals")[0])},StrItem_OnDelAll:function(t){seraph_accel.Ui.TokensList.DelAllItems(jQuery(t.parentNode).closest(".blck").first().find(".vals")[0])},OnUpdateCssAuto:function(t){seraph_accel.Ui.ComboShowDependedItems(t,jQuery(t.parentNode).closest(".blck").first().get(0))},OnLogClear:function(t){return D.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(t,
p){return w.apply(this,arguments)},OnCacheOp:function(t,p){return G.apply(this,arguments)},OnCacheOpCancel:function(t,p){return A.apply(this,arguments)},OnPostUpdCancel:function(t){return E.apply(this,arguments)},OnScheUpdCancel:function(t){return F.apply(this,arguments)},OnExtDbUpdBegin:function(t){return C.apply(this,arguments)},OnExtDbUpdCancel:function(t){return z.apply(this,arguments)},OnQueueDel:function(t,p,q){return L.apply(this,arguments)},OnQueueItemCancel:function(t,p,q){return P.apply(this,
arguments)},OnDataRefreshInit:function(t,p){return R.apply(this,arguments)},OnDataRefresh:function(t,p){return O.apply(this,arguments)},OnHtmlCheck:function(t){return M.apply(this,arguments)}}};(function(){function t(h){return p.apply(this,arguments)}function p(){p=_asyncToGenerator(_regenerator.mark(function r(k){var e,g;return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return e={},l.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"SelfDiag_"+k,{}),cache:!1,dataType:"json"}),l.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:e=l.sent;delete seraph_accel.SelfDiag._int.curAjax;l.next=14;break;case 9:l.prev=9,l.t0=l["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===l.t0.status?e.hr=seraph_accel.Gen.hr.S_ABORTED:(e.hr=seraph_accel.Gen.hr.E_FAIL,e.descr="HTTP "+l.t0.status),500==l.t0.status&&(g=document.implementation.createHTMLDocument(""),g.documentElement.innerHTML=l.t0.responseText,g=g.body.textContent,g=seraph_accel.Gen.StrReplaceAll(g,
"\r",""),g=seraph_accel.Gen.StrReplaceAll(g,["\t","\v"]," "),g=seraph_accel.Gen.StrReplaceAll(g,"\n",". "),(g=seraph_accel.Gen.StrReplaceAllWhileChanging(g,["  ",". . "],[" ",". "]).trim())&&"."!=g&&(e.descr+="<br>"+g));case 14:return l.abrupt("return",e);case 15:case "end":return l.stop()}},r,this,[[1,9]])}));return p.apply(this,arguments)}function q(){q=_asyncToGenerator(_regenerator.mark(function r(k){var e,g,l,m,v,y,b,a,c,n,d,u=arguments;return _regenerator.wrap(function(x){for(;;)switch(x.prev=
x.next){case 0:e=1<u.length&&void 0!==u[1]?u[1]:!1;g=jQuery(k.parentNode).closest(".blck").first();l=g.find(".seraph_accel_spinner");m=g.find('input[type="button"]:not(.cancel)');v=g.find('input[type="button"].cancel');y=g.find(".log");b=[{id:"3rdPartySettCompat",name:f("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:f("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:f("TestName_SetMaxExecTime","admin.SelfDiag",
"seraphinite-accelerator")},{id:"PageOptimize",name:f("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:f("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:f("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];y.empty();for(a=0;a<b.length;a++)c=b[a],y.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",c.name?c.name:c.id),!1));if(!e){x.next=11;break}return x.abrupt("return");case 11:l.show(),m.prop("disabled",
!0),v.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,a=0;case 16:if(!(a<b.length)){x.next=31;break}c=b[a];jQuery(y.children().get(a)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",c.name?c.name:c.id)+f("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));x.next=21;return t(c.id);case 21:n=x.sent;d=f("TestSucc","admin.SelfDiag","seraphinite-accelerator");n.hr!=seraph_accel.Gen.hr.S_OK&&(d=seraph_accel.Gen.hr.Succ(n.hr)?n.hr==seraph_accel.Gen.hr.S_ABORTED?
f("TestAbort","admin.SelfDiag","seraphinite-accelerator"):n.hr==seraph_accel.Gen.hr.S_FALSE?f("TestNotice","admin.SelfDiag","seraphinite-accelerator"):f("TestWarn","admin.SelfDiag","seraphinite-accelerator"):f("TestError","admin.SelfDiag","seraphinite-accelerator"));n.descr&&(d+="<br>"+n.descr);jQuery(y.children().get(a)).replaceWith(seraph_accel.Ui.LogItem(n.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(n.hr)?n.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",
c.name?c.name:c.id)+d,!1));if(seraph_accel.SelfDiag._int.inProgress){x.next=28;break}return x.abrupt("break",31);case 28:a++;x.next=16;break;case 31:l.hide(),m.prop("disabled",!1),v.prop("disabled",!0);case 34:case "end":return x.stop()}},r,this)}));return q.apply(this,arguments)}var f=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(h){return q.apply(this,arguments)},OnCancel:function(h){h=jQuery(h.parentNode).closest(".blck").first();h.find(".seraph_accel_spinner");
h.find('input[type="button"]:not(.cancel)');h.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
